# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master, mac_os_latest, mac_coverage ]
  pull_request:
    branches: [ master, mac_os_latest, mac_coverage ]

jobs:
  build:

    runs-on: macos-10.15
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        git clone https://github.com/yyuu/pyenv.git ~/.pyenv
        PYENV_ROOT="$HOME/.pyenv"
        PATH="$PYENV_ROOT/bin:$PATH"
        eval "$(pyenv init -)"
        PYVER="$(pyenv install --list | grep -E "^\\s*$PYVER" | sort -n -t. -k3 | tail -n1)"
        pyenv install $PYVER
        pyenv global $PYVER
        python --version
    - name: Install PIP
      run: |
        curl -O https://bootstrap.pypa.io/get-pip.py
        python get-pip.py --user
        python -m pip install pip==9.0.3
        python -m pip install six
        pip install codecov coverage pyobjc
    - name: Install test apps
      run: |
        cd apps/MouseTester/macos
        sudo hdiutil attach mousebuttons.dmg
        sudo cp -R /Volumes/mousebuttons/mousebuttons.app /Applications
        sudo hdiutil detach /Volumes/mousebuttons/

        cd apps/SendKeysTester/macos
        sudo hdiutil attach send_keys_test_app.dmg
        sudo cp -R /Volumes/send_keys_test_app/send_keys_test_app.app /Applications
        sudo hdiutil detach /Volumes/send_keys_test_app/

        cd apps/Controls/macos
        sudo hdiutil attach test_app_controls.dmg
        sudo cp -R /Volumes/test_app_controls/ControlsTestAppSB.app /Applications
        sudo hdiutil detach /Volumes/test_app_controls/
    - name: Run tests
      run: |
        python3 pywinauto/unittests/macos/test_ax_element_info_macos.py
